plex:
  PLEX_URL: "http://192.168.111.77:32400"  # change to match your Plex server
  PLEX_TOKEN: "isFgSyj8THjGwnitrzdP"             # get from Plex account or Tautulli
  library_name: "Music"                # name of your music library in Plex

logging:
  level: "INFO"

runtime:
  run_forever: true          # true = loop forever, false = run once
  cache_only: false            # true = only cache metadata and exit
  refresh_interval_minutes: 60
  save_interval: 500
  max_workers: 3             # number of playlists to process in parallel
  build_all_on_start: false   # true = build playlists automatically when services start

tidal:
  token: ""                  # optional override for the default X-Tidal-Token
  country_code: "US"         # optional override for the Tidal country code

allmusic:
  enabled: true
  cache_file: "/app/allmusic_popularity.json"
  timeout: 10
  google_min_interval: 2.0          # seconds to wait between Google requests
  google_backoff_seconds: 30.0      # pause duration after Google returns HTTP 429
