plex:
  PLEX_URL: "http://192.168.111.77:32400"  # change to match your Plex server
  PLEX_TOKEN: "isFgSyj8THjGwnitrzdP"             # get from Plex account or Tautulli
  library_name: "Music"                # name of your music library in Plex

logging:
  level: "INFO"

runtime:
  run_forever: true          # true = loop forever, false = run once
  cache_only: false            # true = only cache metadata and exit
  refresh_interval_minutes: 60
  save_interval: 500
  max_workers: 3             # number of playlists to process in parallel

spotify:
  client_id: "97bfb7998acd470ea0f00886921fc927"
  client_secret: "a014bd8f23f44edfb92d6e3feb05d88e"
  market: "US"                 # optional: ISO 3166-1 alpha-2 market code
  search_limit: 10             # optional: number of search results to evaluate
  cache_file: "/app/spotify_popularity.json"   # optional: persistent cache for Spotify profiles (set to false to disable)
  cache_max_age_days: 30       # optional: refresh cached entries after N days (omit or <=0 to keep forever)

allmusic:
  enabled: true
  cache_file: "/app/allmusic_popularity.json"
  timeout: 10
  google_min_interval: 2.0          # seconds to wait between Google requests
  google_backoff_seconds: 30.0      # pause duration after Google returns HTTP 429
