plex:
  PLEX_URL: "http://192.168.111.77:32400"  # change to match your Plex server
  PLEX_TOKEN: "isFgSyj8THjGwnitrzdP"             # get from Plex account or Tautulli
  library_name: "Music"                # name of your music library in Plex

logging:
  level: "DEBUG"

runtime:
  run_forever: true          # true = loop forever, false = run once
  cache_only: false            # true = only cache metadata and exit
  refresh_interval_minutes: 60
  save_interval: 500

spotify:
  client_id: "your-spotify-client-id"
  client_secret: "your-spotify-client-secret"
  market: "US"                 # optional: ISO 3166-1 alpha-2 market code
  search_limit: 10             # optional: number of search results to evaluate

allmusic:
  enabled: true
  cache_file: "/app/allmusic_popularity.json"
  timeout: 10
